# Generated by Django 3.2.9 on 2021-11-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tradeid', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('user_id', models.IntegerField()),
                ('symobl', models.CharField(max_length=3)),
                ('shares', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
