# Generated by Django 3.2.9 on 2021-11-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBullAPI', '0002_rename_trades_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='Tradeid',
            new_name='Trade_id',
        ),
    ]
